import Head from "next/head";

import Navbar from "../../../components/Navbar";
import Hero from "../../../components/Hero";
import { Box, Heading, Text } from "@chakra-ui/react";

export default function Module101Page() {

  return (
    <>
      <Head>
        <title>PPBL Module 101</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box>
        <Heading>Module 101: Compile your first...</Heading>
        <Text>This is a .tsx file</Text>
      </Box>
    </>
  );
}
